services:
  fastapi:
    build: .
    container_name: fastapi_apm
    env_file:
      - .env
    ports:
      - "8000"
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    depends_on:
      - fastapi
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
