name: Continuous Deployment to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Trigger Deployment on Render
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

      - name: Notify Deployment Success
        if: success()
        run: echo "🚀 Deployment to Render successful!"

      - name: Notify Deployment Failure
        if: failure()
        run: echo "❌ Deployment failed. Check logs for errors."
